### ISSUE TITLE
Cannot run termsteel: ModuleNotFound 'termios'

### ISSUE THREAD

**Issue by Iltotore** [afi-dev/Termsteel#5]
When installing termsteel:
```sh
pip install termsteel
```

then running `termsteel` I get the following error:
```
Traceback (most recent call last):
  File "C:\users\rapha\appdata\local\programs\python\python38-32\lib\runpy.py", line 192, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\users\rapha\appdata\local\programs\python\python38-32\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\rapha\AppData\Local\Programs\Python\Python38-32\Scripts\termsteel.exe\__main__.py", line 4, in <module>
  File "C:\users\rapha\appdata\local\programs\python\python38-32\lib\site-packages\termsteel\app.py", line 9, in <module>
    import pty
  File "C:\users\rapha\appdata\local\programs\python\python38-32\lib\pty.py", line 11, in <module>
    import tty
  File "C:\users\rapha\appdata\local\programs\python\python38-32\lib\tty.py", line 5, in <module>
    from termios import *
ModuleNotFoundError: No module named 'termios'
```

I am using Python 3.8 on Windows 10 with WSL 2

**Comment by kaelianbaudelet** [comment]
Hi [Iltotore](https://github.com/Iltotore)

I think you have installed **Termsteel** out of a subsystem, indeed you need to have **WSL** but you **also need linux environment to run Termsteel such as Debian or Ubuntu** that you can download very easily via the **Microsoft store**, I invite you to follow this page which explains you how to install it via wsl : [🔗 Install via WSL](https://github.com/afi-dev/Termsteel/wiki/Install-Termsteel#user-content-windows-wsl2)

📖 Feel free to refer to the [🔗 Troubleshouting page](https://github.com/afi-dev/Termsteel/wiki/Troubleshooting) to see what your problem is, I expressly wrote it to help Termsteel users

👉👈 I want to apologize personally for the fact that there is no version specific native to **Windows** and for the inconvenience caused, but I plan to make a version dedicated to Windows in a **future update** and a version compatible with **Docker**.

🙂 If you have other concerns or questions related to Termstel do not hesitate I am here for that.

More Sincerely, Afi 🙃

**Comment by Iltotore** [comment]
Hello 👋 

I already mentioned that I also tested termsteel on WSL 2:
> I am using Python 3.8 on Windows 10 with WSL 2

but I get the exact same error.

Regards.

**Comment by kaelianbaudelet** [comment]
Hi, welcome back 👋 [Iltotore](https://github.com/Iltotore) 

Are you really sure you have wsl2 but you have to launch this in a **linux environment** and **not in a simple Windows terminal via powershell or cmd**, I am very surprised if you receive this error on a Linux system because it is a module integrated by default in python for the linux version, which I deduce that you did not launch it from a debian or ubuntu environment... If this is not the case I invite you to send me a screenshot showing that you run it on WSL2 via Debian or Ubuntu installed as described [here](https://github.com/afi-dev/Termsteel/wiki/Install-Termsteel#user-content-windows-wsl2)

Make sure you have done the following: 

First check you have WSL installed by using this command in Powershell CMD : 

```powershell
PS C:\Users\You> wsl.exe --status
```
You shoud have this normaly : 
```
Default distribution: Debian
Default version: 2

The last update of the Windows Subsystem for Linux was done on 03/27/2022
Automatic WSL updates are enabled.
``` 
So make sure you have WSL version 2 by looking at the default version field. Also think to check that a subsystem exists on your machine by the default distribution field (in my case I have Debian as subsystem)

If you do not see a sub-system by default sela simply means that you have not installed a sub-system wsl2 for this nothing more simple go to the Windows Store and install the sub-system of your choice of type Linux, you have the choice bymit many distribution in sub-system. Among them there is Debian, Ubuntu, KaliLinux and etc.. I strongly recommend Debian, install it and open it, a terminal will appear and ask you for a username and password, choose one and once done install python & the curl tool and pip using the following command (DO NOT RUN THIS INSIDE ANOTHER CMD LIKE POWERSHELL OR WINCMD, JUST RUN INTO YOUR SUB-SYSTEM SHELL)

```
sudo apt-get update -y && sudo apt-get install python3 -y && sudo apt-get install curl -y && sudo apt-get install python3-pip -y
```

Once installed, run the installation script via this command: 

```
curl -sSL https://raw.githubusercontent.com/afi-dev/Termsteel/main/installer.sh | sudo bash
```

Normally everything should work.

If you are really sure that you have run the installer from a debian type linux environment from WSL and that you get this error. Contact me quickly on Github via this issue and send me a screen showing your error

See this video to help to check if u have wsl2 and debian or another sub-system installed: 

https://user-images.githubusercontent.com/44731817/187547768-eb6e1d49-a4b3-47a0-9b99-bf75368a27b6.mp4

More Sincerely, Afi 🙃

**Comment by Iltotore** [comment]
> Are you really sure you have wsl2 but you have to launch this in a linux environment and not in a simple Windows terminal via powershell or cmd, 

I am launching it from WSL terminal.

Here is my WSL status:
```
Distribution par défaut : Debian
Version par défaut : 2
Activez la fonctionnalité Windows de plateforme de machine virtuelle et assurez-vous que la virtualisation est activée dans le BIOS.
Pour plus d’informations, rendez-vous sur https://aka.ms/wsl2-install
```

Here is my neofetch:
```
       _,met$$$$$gg.          root@DESKTOP-AAJC3R4
    ,g$$$$$$$$$$$$$$$P.       --------------------
  ,g$$P"     """Y$$.".        OS: Debian GNU/Linux 11 (bullseye) on Windows 10 x86_64
 ,$$P'              `$$$.     Kernel: 4.4.0-19041-Microsoft
',$$P       ,ggs.     `$$b:   Uptime: 4 secs
`d$$'     ,$P"'   .    $$$    Packages: 1313 (dpkg)
 $$P      d$'     ,    $$P    Shell: bash 5.1.4
 $$:      $$.   -    ,d$$'
 $$;      Y$b._   _,d$P'
 Y$$.    `.`"Y$$$$P"'
 `$$b      "-.__
  `Y$$
   `Y$$.
     `$$b.
       `Y$$b.
          `"Y$b._
              `"""
```

Edit: probably got a corrupted python lib. I removed all of them and reinstalled a clean Python 3. Works like a charm.

**Comment by kaelianbaudelet** [comment]
Hey, [Iltotore](https://github.com/Iltotore)

I think i have found your problem.

You have not enabled virtualization from the BIOS, please enable VT-X for your Intel processor or AMD-v for your AMD processor in BIOS. I must admit that this is the first time I have seen someone having problems with termios, so I put my hand down that it is a problem with your WSL because termios is a module by default. So try to enable VT-X or AMD-V and tell me if this work after... 

More Sincerely, Afi 🙃

**Comment by kaelianbaudelet** [comment]
[Iltotore](https://github.com/Iltotore), 

If your problem persists I invite you to try on a real Linux or MacOS support or to wait for a future update of Termsteel containing the Windows support.

It also seems that you are French so if you want to contact me via Discord by adding `Afi#1523` to discuss (because I am also French) 

More Sincerely, Afi 🙃

**Comment by Iltotore** [comment]
Read my edit 😛: A complete reinstall of Python solved the issue. I guess it was due to a broken or missing std module.
